name: Codex Apply Changes

on:
  workflow_dispatch:

jobs:
  apply-codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: codex-output   # work on the codex-output branch
      - name: Apply Codex Patch
        run: |
          echo "${{ github.event.inputs.patch }}" > codex.patch
          git apply codex.patch || echo "⚠️ No patch applied"
          git config user.name "Codex Bot"
          git config user.email "codex-bot@example.com"
          git add .
          git commit -m "Apply Codex changes" || echo "Nothing to commit"
          git push origin codex-output
